miapp/urls.py
from django.urls import path
from . import views

app_name = 'miapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
]

webpersonal/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('miapp.urls')),  # Incluye las URLs de tu aplicación miapp
]

# Configuración para servir archivos estáticos y multimedia durante el desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

miapp/models.py
# En el archivo models.py de tu aplicación miapp

import os
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_delete
from django.dispatch import receiver

class Facultad(models.Model):
    nombre = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to='facultad/', null=True,blank=True)

    def __str__(self):
        return self.nombre
@receiver(post_delete, sender=Facultad)
def delete_facultad_image(sender, instance, **kwargs):
    if instance.imagen:
        if os.path.isfile(instance.imagen.path):
            os.remove(instance.imagen.path)
    

    

class Carrera(models.Model):
    facultad = models.ForeignKey(Facultad, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)

class Perfil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    foto_perfil = models.ImageField(upload_to='perfil/', null=True, blank=True)
    foto_banner = models.ImageField(upload_to='banner/', null=True, blank=True)

    def __str__(self):
        return self.user.username


class Foto_extras(models.Model):
    foto = models.ImageField(upload_to='extras/')
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE)

class Interes(models.Model):
    nombre = models.CharField(max_length=45)

class PersonaInteres(models.Model):
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    interes = models.ForeignKey(Interes, on_delete=models.CASCADE)

class Matches(models.Model):
    usuario1 = models.ForeignKey(Perfil, related_name='matches_usuario1', on_delete=models.CASCADE)
    usuario2 = models.ForeignKey(Perfil, related_name='matches_usuario2', on_delete=models.CASCADE, null=True)
    fecha = models.DateField(auto_now_add=True)
    activo = models.BooleanField(default=True)

class Mensaje(models.Model):
    matches = models.ForeignKey(Matches, on_delete=models.CASCADE)
    chat = models.CharField(max_length=300)
    mensaje = models.TextField(default="")
    foto = models.ImageField(upload_to='mensajes/', null=True, blank=True)
    video = models.CharField(max_length=300, null=True, blank=True)
    leido = models.BooleanField(default=False)
    fecha = models.DateField(auto_now_add=True)
    hora = models.TimeField(auto_now_add=True)
    usuario = models.CharField(choices=[("1", "1"), ("2", "2")], max_length=1)

miapp/forms.py
# forms.py
from django import forms 
from .models import Perfil
from django.contrib.auth.models import User

class PerfilForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = ['foto_perfil', 'foto_banner']

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

miapp/views.py
# views.py
from django.shortcuts import render, redirect 
from .models import Perfil
from django.contrib.auth.models import User
from .forms import UserForm, PerfilForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from .models import Facultad

def index(request):
    correo = ""
    if request.method == 'POST':
        correo = request.POST.get('correo')
        contrasena = request.POST.get('contrasena')
    
        usuario = authenticate(request, username=correo, password=contrasena)

        if usuario is not None:
            login(request, usuario)
            # Mensaje en consola
            print(f"El usuario {usuario.username} ha iniciado sesión correctamente.")
            next_url = request.GET.get('next')
            if next_url:
                return redirect(next_url)
            else:
                return redirect('./home')
        else:
            # Mensaje en consola para el caso de inicio de sesión fallido
            print("Inicio de sesión fallido. Credenciales incorrectas.")

    data = {
        'titulo': "MatchUTM"
    }
    
    return render(request, 'miapp/index.html', data)

# home 
def home(request):
    data = {
        'titulo': 'Habitacion',
        'facultades': Facultad.objects.all()
    }
    return render(request, 'miapp/home.html', data)

# PERFIL

@login_required
def profile(request):
    if request.method == 'POST':
        perfil_form = PerfilForm(request.POST, request.FILES, instance=request.user.perfil)
        if perfil_form.is_valid():
            perfil_form.save()
            return redirect('miapp:profile')
    else:
        perfil_form = PerfilForm(instance=request.user.perfil)
    
    context = {
        'perfil_form': perfil_form
    }
    return render(request, 'miapp/profile.html', context)


miapp/templates/miapp/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ titulo }}</title>
    <!-- Enlazar estaticos css-->
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
     <!-- Enlazar JavaScript -->
    <script defer src="{% static 'javascript/home.js' %}"></script>

</head>

<body>
    <div class="barra-navegacion">
        <!-- -----------------------------LADO IZQUIERDO------------------------------->
        <div class="nav-izquierda">
            <!-- Boton clic (Al apretar de despleja lo del desplegable 1)-->
             
                <img src="{% static 'imagenes/home_img/Menu.svg' %}" alt="Menu" class="agrandar" onclick="toggleMenu_general()">
            
            <!-- Boton para notificaciones -->
                <img src="{% static 'imagenes/home_img/Notificacion.svg' %}" alt="Notificaciones" class="icono agrandar" onclick="toggleMenuNotificaciones()">

            <!-- Boton para la página de inicio -->
            <a href="{% url 'miapp:home' %}">
                <img src="{% static 'imagenes/home_img/Home.svg' %}" alt="Inicio" class="agrandar" >
            </a>

            <!-- Boton para acceder al apartado de perfil-->

            <!-- Boton para acceder al apartado de perfil-->
            <a href="{% url 'miapp:profile' %}">
                <img src="{% if request.user.perfil.foto_perfil %}{{ request.user.perfil.foto_perfil.url }}{% else %}{% static 'path/to/default/profile_picture.jpg' %}{% endif %}" alt="Perfil" class="icono foto-perfil agrandar">
            </a>
            
            

        </div>

        <!-- --------------------------LOOPS------------------------------- -->
        <div class="fondo">
                <div class="rectangulo_loops" id="rectangulo_loops">
                    <button class="boton_navegacion-loops agrandar" id="boton_navegacion-loops" 
                            desplejable1-src="{% static 'imagenes/home_img/Desplejable2.svg' %}"
                            desplejable2-src="{% static 'imagenes/home_img/Desplejable.svg' %}">
                        <img src="{% static 'imagenes/home_img/Desplejable.svg' %}" alt="Expand" id="desplejable3-src">
                    </button>
                </div>

                <div class="contenedor-loops">
                    <!-- Contenido del video aquí -->
                    <div class="icons-loos">
                        <div class="icon-circle agrandar">
                            <img src="{% static 'imagenes/home_img/fechaizq.svg' %}" alt="Flecha Izquierda">                         
                        </div>

                        <div class="icon-circle agrandar">
                            <img src="{% static 'imagenes/home_img/graduacion.svg' %}" alt="Configuración">
                        </div>

                        <div class="icon-circle agrandar">
                            <img src="{% static 'imagenes/home_img/zoom.svg' %}" alt="Maximizar">
                        </div>

                        <div class="icon-circle agrandar">
                            <img src="{% static 'imagenes/home_img/corazon.svg' %}" 
                            alt="Like" style="height: 35px; width: 35px;" >
                        </div>

                        <div class="icon-circle agrandar">
                            <img src="{% static 'imagenes/home_img/der.svg' %}" alt="Flecha Derecha">
                        </div>

                    </div>
                </div>
            
        </div>

        


        <!-- Botones (Enlaces de arriba)-->
        <div class="nav-centro">

            <!-- DIRECCIONAR A LA PLANTILLA MENSAJE-->
            <a href="#" style="text-decoration: none; color: #898282;">
                <div class="a2 enlace-color" >Mensaje</div>
            </a>
            <!-- DIRECCIONAR A LA PLANTILLA PUBLICACION-->
            <a href="#" style="text-decoration: none; color: #898282;">
                <div class="a2 enlace-color" >Publicacion</div>
            </a>
            <!-- DIRECCIONAR A LA PLANTILLA LOOPS-->
            <a href="#" style="text-decoration: none; color: #898282;">
                <div class="a2 enlace-color" >Loops</div>
            </a>

        </div>

        <!----------------------------Lado derecho--------------------------------->
        <a href="../home/" style="text-decoration: none; color: #ffffff;">
            <div class="nav-derecha enlace-color">
                <div class="logo">MatchUTM</div>
                <img src="{% static 'imagenes/home_img/Logo.svg' %}" alt="Logo UTM" class="logo-utm">
            </div>
        </a>


    </div>
    


       <!-- FIN DE LOS MARCOS DE LOS LOOPS--> 

       <!--  MENU PRUEBA 3 RAYITAS-->
       <div id="menu-cuadro" class="menu-cuadro">
        <a href="#">Ceress79</a>
        <a href="#">Configuracion</a>
        <a href="#">No se q poner :v</a>
        <!-- Agrega más enlaces según sea necesario -->
        </div>

    </div>

    <!-- Fondo oscuro -->
    <div id="fondo-oscuro" class="fondo-oscuro"></div>

    <!-- Contenedor de notificaciones -->
    <div id="menu-notificaciones" class="menu-notificaciones">
        <h2>Notificaciones</h2>
        <div class="notificacion">Notificación 1</div>
        <div class="notificacion">Notificación 2</div>
        <div class="notificacion">Notificación 3</div>
    </div>


    <!-- Contenido de la pagina principal, Tarjetas de facultades, etc...-->    
    <div class="contenido-principal">
        <div class="contenido ">
            <div class="promociones ">
                <img src="{% static 'imagenes/home_img/Promocion.gif' %}" alt="Promociones">
            </div>

            <!-- Lista de tarjetas de facultades -->
            {% for facultad in facultades %}
            <div class="tarjeta-facultad agrandar_contenido">
                <img src="{{ facultad.imagen.url }}" alt="Facultad {{ forloop.counter }}">
                <div class="nombre-facultad">{{ facultad.nombre }}</div>
            </div>
            {% empty %}
            <p>Actualmente no hay facultades, somos pobres</p>
            {% endfor %}
        </div>
    </div>

    
</body>
</html>

miapp/templates/miapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ titulo }}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">  <!-- Enlace al archivo CSS externo -->
</head>
<body>
    <div class="cuadro"></div>

    <div class="cuadro Roboto message">
        <div style="top: 50%; left: 50%; transform: translate(-13%, -50%);">
            <div style="position:absolute; margin-top: -7rem; margin-left:11.7rem;">
                <img src="{% static 'imagenes/logo.webp' %}" alt="Logo" width="280">
            </div>
            <div style="margin-left: 10rem; margin-top:10rem;">
                <h2 class="Roboto" style="color: white">Match<h style="color:rgb(255, 0, 81)">UTM</h></h2>
            </div>
        </div>

        <form method="post">
            {% csrf_token %}
            <div style="position: absolute; margin-top: -60px;"> 
                <p style="font-size: 22px; margin-left: 5rem; color: aliceblue;">Correo Institucional</p>
                <input style="top:3.2rem" class="input2" type="email" name="correo" placeholder="iquimi9873@utm.edu.ec" required>
            </div>
            
            <div style="position: absolute; margin-top: 60px;">
                <p style="font-size: 22px; margin-top: 4px; margin-left: 5rem; color: aliceblue;">Contraseña</p>
                <input type="password" style="top:2rem" class="input2" name="contrasena" placeholder="pepito1234" required>
            </div>

            <button class="cuadro13" style="color: rgb(255, 255, 255);"><b>Iniciar<br>Sesion</b></button>
        </form>
    </div>
</body>
</html>

miapp/templates/miapp/profile.html
<!-- profile.html -->
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Perfil</title>
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <script defer src="{% static 'javascript/home.js' %}"></script>
</head>

<body>



    <div class="barra-navegacion">
        <!-- -----------------------------LADO IZQUIERDO------------------------------->
        <div class="nav-izquierda">
            <!-- Boton clic (Al apretar de despleja lo del desplegable 1)-->

            <img src="{% static 'imagenes/home_img/Menu.svg' %}" alt="Menu" class="agrandar"
                onclick="toggleMenu_general()">

            <!-- Boton para notificaciones -->
            <img src="{% static 'imagenes/home_img/Notificacion.svg' %}" alt="Notificaciones" class="icono agrandar"
                onclick="toggleMenuNotificaciones()">

            <!-- Boton para la página de inicio -->
            <a href="{% url 'miapp:home' %}">
                <img src="{% static 'imagenes/home_img/Home.svg' %}" alt="Inicio" class="agrandar">
            </a>

            <!-- Boton para acceder al apartado de perfil-->
            <a href="{% url 'miapp:profile' %}">
                <img src="{% if request.user.perfil.foto_perfil %}{{ request.user.perfil.foto_perfil.url }}{% else %}{% static 'path/to/default/profile_picture.jpg' %}{% endif %}" alt="Perfil" class="icono foto-perfil agrandar">
            </a>
            
            
        </div>

        <!-- --------------------------LOOPS------------------------------- -->
        <div class="fondo">
            <div class="rectangulo_loops" id="rectangulo_loops">
                <button class="boton_navegacion-loops agrandar" id="boton_navegacion-loops"
                    desplejable1-src="{% static 'imagenes/home_img/Desplejable2.svg' %}"
                    desplejable2-src="{% static 'imagenes/home_img/Desplejable.svg' %}">
                    <img src="{% static 'imagenes/home_img/Desplejable.svg' %}" alt="Expand" id="desplejable3-src">
                </button>
            </div>

            <div class="contenedor-loops">
                <!-- Contenido del video aquí -->
                <div class="icons-loos">
                    <div class="icon-circle agrandar">
                        <img src="{% static 'imagenes/home_img/fechaizq.svg' %}" alt="Flecha Izquierda">
                    </div>

                    <div class="icon-circle agrandar">
                        <img src="{% static 'imagenes/home_img/graduacion.svg' %}" alt="Configuración">
                    </div>

                    <div class="icon-circle agrandar">
                        <img src="{% static 'imagenes/home_img/zoom.svg' %}" alt="Maximizar">
                    </div>

                    <div class="icon-circle agrandar">
                        <img src="{% static 'imagenes/home_img/corazon.svg' %}" alt="Like"
                            style="height: 35px; width: 35px;">
                    </div>

                    <div class="icon-circle agrandar">
                        <img src="{% static 'imagenes/home_img/der.svg' %}" alt="Flecha Derecha">
                    </div>

                </div>
            </div>

        </div>

        <!-- Botones (Enlaces de arriba)-->
        <div class="nav-centro">

            <!-- DIRECCIONAR A LA PLANTILLA MENSAJE-->
            <a href="#" style="text-decoration: none; color: #898282;">
                <div class="a2 enlace-color">Mensaje</div>
            </a>
            <!-- DIRECCIONAR A LA PLANTILLA PUBLICACION-->
            <a href="#" style="text-decoration: none; color: #898282;">
                <div class="a2 enlace-color">Publicacion</div>
            </a>
            <!-- DIRECCIONAR A LA PLANTILLA LOOPS-->
            <a href="#" style="text-decoration: none; color: #898282;">
                <div class="a2 enlace-color">Loops</div>
            </a>

        </div>

        <!----------------------------Lado derecho--------------------------------->
        <a href="../home/" style="text-decoration: none; color: #ffffff;">
            <div class="nav-derecha enlace-color">
                <div class="logo">MatchUTM</div>
                <img src="{% static 'imagenes/home_img/Logo.svg' %}" alt="Logo UTM" class="logo-utm">
            </div>
        </a>


    </div>



    <!-- FIN DE LOS MARCOS DE LOS LOOPS-->

    <!--  MENU PRUEBA 3 RAYITAS-->
    <div id="menu-cuadro" class="menu-cuadro">
        <a href="#">Ceress79</a>
        <a href="#">Configuracion</a>
        <a href="#">No se q poner :v</a>
        <!-- Agrega más enlaces según sea necesario -->
    </div>

    </div>

    <!-- Fondo oscuro -->
    <div id="fondo-oscuro" class="fondo-oscuro"></div>

    <!-- Contenedor de notificaciones -->
    <div id="menu-notificaciones" class="menu-notificaciones">
        <h2>Notificaciones</h2>
        <div class="notificacion">Notificación 1</div>
        <div class="notificacion">Notificación 2</div>
        <div class="notificacion">Notificación 3</div>
    </div>

    <div class="contenido-principal">
        <div class="contenido">

            <div class="profile-banner">
                <!-- Banner de fondo -->
                <div class="banner-image" id="bannerImage" {% if request.user.perfil.foto_banner %}
                    style="background-image: url('{{ request.user.perfil.foto_banner.url }}')" {% endif %}>
                    <!-- Icono de cambiar banner -->
                    <button class="change-banner-btn" onclick="openBannerModal()">
                        <img src="{% static 'imagenes/profile_img/default_banner.svg' %}" alt="Editar Banner" class="agrandar">
                    </button>
                </div>

                <div>
                    <!-- Foto de perfil -->
                    <div class="profile-picture">
                        <img
                            src="{% if request.user.perfil.foto_perfil %}{{ request.user.perfil.foto_perfil.url }}{% else %}{% static 'path/to/default/profile_picture.jpg' %}{% endif %}">
                        <!-- Icono de cambiar foto de perfil -->
                    </div>
                    <button class="change-profile-btn" onclick="openProfileModal() ">
                        <img src="{% static 'imagenes/profile_img/camara.svg' %}" alt="Cambiar foto" class="agrandar">
                    </button>
                </div>
            </div>

            <!-- Modales para cambiar foto de perfil y banner de fondo -->
            <div id="bannerModal" class="modal">
                <div class="modal-content">
                    <span class="close" onclick="closeBannerModal()">&times;</span>
                    <h2>Cambiar banner de fondo</h2>
                    <form method="POST" enctype="multipart/form-data" action="{% url 'miapp:profile' %}">
                        {% csrf_token %}
                        <input type="file" id="bannerInput" name="foto_banner" accept="image/*">
                        <button type="submit">Guardar</button>
                    </form>
                </div>
            </div>

            <div id="profileModal" class="modal">
                <div class="modal-content">
                    <span class="close" onclick="closeProfileModal()">&times;</span>
                    <h2>Cambiar foto de perfil</h2>
                    <form method="POST" enctype="multipart/form-data" action="{% url 'miapp:profile' %}">
                        {% csrf_token %}
                        <input type="file" id="profileInput" name="foto_perfil" accept="image/*">
                        <button type="submit">Guardar</button>
                    </form>
                </div>
            </div>

            <div class="barra-opciones">

                <a href="#" style="text-decoration: none; color: #ded2d2;">
                    <div class="a1 enlace-color">Prestigio</div>
                </a>


                <a href="#" style="text-decoration: none; color: #ded2d2;">
                    <div class="a1 enlace-color">Informacion</div>
                </a>


                <a href="#" style="text-decoration: none; color: #ded2d2;">
                    <div class="a1 enlace-color">Fotos y Videos</div>
                </a>


                <a href="#" style="text-decoration: none; color: #ded2d2;">
                    <div class="a1 enlace-color">Matches</div>
                </a>

            </div>





            <!-- JavaScript para controlar los modales -->
            <script defer src="{% static 'javascript/profile.js' %}"></script>
        </div>
    </div>
</body>

</html>